// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHHdRnAr36UTmnhmaO1Ox9Uzm0xUiUz4',
    appId: '1:66884138887:web:408107c04bd3dd20788522',
    messagingSenderId: '66884138887',
    projectId: 'job-timer-app-dw',
    authDomain: 'job-timer-app-dw.firebaseapp.com',
    storageBucket: 'job-timer-app-dw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnN_N0QEoKj7vbR7ytLUZuS26s5iniJxg',
    appId: '1:66884138887:android:04c2e0071c9650c3788522',
    messagingSenderId: '66884138887',
    projectId: 'job-timer-app-dw',
    storageBucket: 'job-timer-app-dw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyaERtATBmbaTArTfXkxXE7vKfAXSOeE4',
    appId: '1:66884138887:ios:c59e5ab8c4075a27788522',
    messagingSenderId: '66884138887',
    projectId: 'job-timer-app-dw',
    storageBucket: 'job-timer-app-dw.appspot.com',
    iosClientId: '66884138887-ephrcodabqc7qqrs53u2215msvv0t1qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJobTimerDw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyaERtATBmbaTArTfXkxXE7vKfAXSOeE4',
    appId: '1:66884138887:ios:c59e5ab8c4075a27788522',
    messagingSenderId: '66884138887',
    projectId: 'job-timer-app-dw',
    storageBucket: 'job-timer-app-dw.appspot.com',
    iosClientId: '66884138887-ephrcodabqc7qqrs53u2215msvv0t1qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJobTimerDw',
  );
}
